name = "MyPkg"
uuid = "f6f73acc-c508-4daa-b637-0f9914d3594c"
authors = ["Praveen Kumar Yalakati <praveen.yalkati77.yj@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
